### ISSUE TITLE
Ikea Tradfri Remote missing scenes

### ISSUE THREAD

**Issue by meisterfuu** [WebThingsIO/zigbee-adapter#199]
I got a Tradfri Remote(the one with 5 buttons; E1524) last year. It paired perfectly and everything worked. 
Today i got a new one. The number on the underside changed: E1810. As far as I know the only difference is, that it is suited for use in a bathroom now. But now the scene buttons(left/right) were not working and did not show up in the ui too.

In the attachment you can see the configurations the gateway created. I was able to fix the problem by making a copy of the old one and only adjusting addr64 and addr16. Now everything works perfectly.

I hope this is of some help.

[tradfri_remote_new.txt](https://github.com/mozilla-iot/zigbee-adapter/files/4395068/tradfri_remote_new.txt)
[tradfri_remote_old.txt](https://github.com/mozilla-iot/zigbee-adapter/files/4395069/tradfri_remote_old.txt)

Edit: I use a Conbee II USB Dongle

**Comment by chas-iot** [comment]
I created a draft pull request for this

**Comment by chas-iot** [comment]
This is fixed in the latest release 0.11.13 from Friday
