### ISSUE TITLE
No Zigbee dongle found on Webthings

### ISSUE THREAD

**Issue by alvpcardoso** [WebThingsIO/zigbee-adapter#260]
There was a closed issue with the same problem so I had to open a new one.

Everything was running fine. I left Webthings for a few days, and when I connected the Conbee to the Raspberry PI, I saw the message.

I downloaded a new image, flashes a SD card and started all over again. The result is the same:

`2020-12-03 14:52:48.965 ERROR  : zigbee-adapter: SerialProber: timeout: deConz dongle not detected on /dev/ttyACM0
2020-12-03 14:52:48.967 INFO   : zigbee-adapter: Serial ports that were found:
2020-12-03 14:52:49.111 INFO   : zigbee-adapter: USB Serial Device 1cf1:0030 Vendor: dresden elektronik ingenieurtechnik GmbH Serial: DE2228199 found @ /dev/ttyACM0
2020-12-03 14:52:49.113 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyAMA0
2020-12-03 14:52:49.115 INFO   : zigbee-adapter: Serial Device found @ /dev/ttyS0
2020-12-03 14:52:49.116 ERROR  : zigbee-adapter: Failed to start add-on zigbee-adapter: No Zigbee dongle found`

**Comment by frederic34** [comment]
https://github.com/WebThingsIO/serial-prober-node/issues/11

**Comment by alvpcardoso** [comment]
There is another issue open. Closing this one.

**Comment by chas-iot** [comment]
Is this a brand new device or did you upgrade the firmware on the device?
If yes, then we know the cause - The firmware has changes to the serial protocol that need work to support. I'm following up with the manufacturer at https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3787 and our tracker issue is at https://github.com/WebThingsIO/serial-prober-node/issues/11

**Comment by alvpcardoso** [comment]
> 
> 
> Is this a brand new device or did you upgrade the firmware on the device?
> If yes, then we know the cause - The firmware has changes to the serial protocol that need work to support. I'm following up with the manufacturer at [dresden-elektronik/deconz-rest-plugin#3787](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3787) and our tracker issue is at [WebThingsIO/serial-prober-node#11](https://github.com/WebThingsIO/serial-prober-node/issues/11)

The problem was there before updating the firmware. Let's say I left the Conbee without use for a few weeks and when I started to use it again, the adapter did not start. Now both Webthings and Conbee are updated.
