### ISSUE TITLE
Phillips Hue Color White&Ambience (E27) temperature and brightness not working

### ISSUE THREAD

**Issue by marius-se** [WebThingsIO/zigbee-adapter#274]
Hey, I’m currently trying to control my Phillips Hue White/Ambience (Color, E27) via the Webthings gateway. My setup: RaspberryPi Webthings image + TI CC2532 as a Zigbee dongle + Webthings Zigbee adapter. Works perfectly fine! I managed to connect the bulb, turn it on and off and change the color.

Now what is missing is the brightness and temperature button. Any ideas how to get them? Through the Phillips Hue app, connected via Bluetooth, I have full control.

Many thanks in advance!

**Comment by mrstegeman** [comment]
@marius-se Does this work now, with version 0.15.8?

**Comment by marius-se** [comment]
Unfortunately I switched back to HomeAssistant as too many things weren't working as expected. If I have more time available I'll give it another try. I don't know tho when (/if) this will happen. Sorry!
