### ISSUE TITLE
LIDL Livarno Lux Lights - Color Temperature not working

### ISSUE THREAD

**Issue by frankduiker** [WebThingsIO/zigbee-adapter#282]
I have a few color temperature lights. Brand=LIDL Livarno Lux, Model=HG06492A controlled by the Webthings Gateway on a RaspberryPI 3B+ and a Conbee II  . The color temperature of the light cannot be controlled by the webthings application. The other properties of the light (On/Off and Level Control) work fine.

If I run the deCONZ app everything work fine. The light are recognized as Color Temperature Lights and can be modified as expected.
![lidl_light_color_control](https://user-images.githubusercontent.com/13468733/107789084-748b5900-6d51-11eb-8cc8-39d948275030.jpg)

![lidl_light_phoscon_app](https://user-images.githubusercontent.com/13468733/107790437-0b0c4a00-6d53-11eb-9ed6-305ae923678c.jpg)

This is part of my the nodes configuration file (zb-00212effff06c503.json);
  "588e81fffee0f50f": {
      "addr64": "588e81fffee0f50f",
      "addr16": "e591",
      "activeEndpoints": {
        "1": {
          "profileId": "0104",
          "deviceId": "010c",
          "deviceVersion": 1,
          "inputClusters": [
            "0000",
            "0003",
            "0004",
            "0005",
            "0006",
            "0008",
            "0300",
            "1000"
          ],
          "outputClusters": [
            "0019",
            "000a"
          ],
          "classifierAttributesPopulated": true
        },
        "242": {
          "profileId": "a1e0",
          "deviceId": "0061",
          "deviceVersion": 0,
          "inputClusters": [],
          "outputClusters": [
            "0021"
          ],
          "classifierAttributesPopulated": true
        }
      },
      "properties": {
        "level": {
          "name": "level",
          "value": 54.4,
          "visible": true,
          "title": "Brightness",
          "type": "number",
          "@type": "BrightnessProperty",
          "unit": "percent",
          "minimum": 0,
          "maximum": 100,
          "multipleOf": 0.1,
          "links": [],
          "profileId": 260,
          "endpoint": 1,
          "clusterId": 8,
          "attr": "currentLevel",
          "attrId": 0,
          "fireAndForget": false,
          "bindNeeded": false,
          "configReportNeeded": false,
          "initialReadNeeded": false,
          "level": 138
        },
        "on": {
          "name": "on",
          "value": true,
          "visible": true,
          "title": "On/Off",
          "type": "boolean",
          "@type": "OnOffProperty",
          "links": [],
          "profileId": 260,
          "endpoint": 1,
          "clusterId": 6,
          "attr": "onOff",
          "attrId": 0,
          "fireAndForget": false,
          "bindNeeded": false,
          "configReportNeeded": false,
          "initialReadNeeded": false
        }
      },
      "name": "zb-588e81fffee0f50f-light",
      "type": "light",
      "@type": [
        "Light",
        "OnOffSwitch"
      ],
      "defaultName": "zb-588e81fffee0f50f-light",
      "extendedTimeout": true,
      "activeEndpointsPopulated": true,
      "nodeInfoEndpointsPopulated": true,
      "colorMode": 2,
      "modelId": "TS0502A",
      "powerSource": 1,
      "rxOnWhenIdle": 1
    },

**Comment by frankduiker** [comment]
It seems that ColorTemperature is implemented for ZLL devices, but not for ZHA devices. Changes are needed in zb-classifier.js and zb-constants.js

**Comment by frankduiker** [comment]
I have the solution, but I am not a collaborator on this project.
Can somebody tell me how to get invited to this project ?

**Comment by chas-iot** [comment]
If the solution is one or two lines of code, just post here and we can create a PR. If it is more complex, or you would prefer to keep attribution, then:

- Fork this repository - there's a button at the top right of the page
- create a commit with your solution in your fork
- Submit the commit as a PR, then @mrstegeman or another committer can comment and, when ready, approve and apply the PR.
