### ISSUE TITLE
Provide a mechanism to disable the adapter taking control of the dongle serial ports so that zigbee2mqtt can access them

### ISSUE THREAD

**Issue by chas-iot** [WebThingsIO/zigbee-adapter#308]
If there is a dongle plugged in that can be used by both zigbee-adapter and zigbee2mqtt then it is not possible to test the new code.

Much more difficult use case: I have two ConBee II dongles, so I could, in theory, attach one to each. However this would require much deeper intervention at the OS level (udev rules) to provide alternate symlink device names and specifically configure zigbee-adapter to use one and zigbee2mqtt to use another.

**Comment by tim-hellhake** [comment]
I added two new settings which allow you to specify exactly which sticks to use.

**Comment by chas-iot** [comment]
It looks like this will do the trick. When do you expect to merge this release into the addon-list?

**Comment by tim-hellhake** [comment]
Now :grimacing:

**Comment by chas-iot** [comment]
There is a major unannounced backwards compatibility break :(
"Automatic probing of the serial ports" defaults to cleared, which means that anyone non-technical still using the legacy adapter (perhaps with an incompatible dongle) will see all of the zigbee devices stop working with no explanation. This should be widely announced and the description of the setting should help users understand what to do.
I'm busy at day job today, so can't dig in with a patch

**Comment by tim-hellhake** [comment]
It looks like the default value has no effect.
I converted the activate flag to a reactive flag, so probing is activated unless explicitly deactivated.

**Comment by tim-hellhake** [comment]
As soon as the build is finished I release the fix.
