### ISSUE TITLE
Zigbee adapter crashes when changing color of a bulb

### ISSUE THREAD

**Issue by AlanDThiessen** [WebThingsIO/zigbee-adapter#48]
The Zigbee adapter is crashing with Assertion errors every time the user attempts to change the color of a Philips Hue bulb.  "Expecting endpoint to be a number" from zb-node.js line 1282.  Current version of the gateway is 0.5.2.

Please see attached log.
[ZigbeeCrashLog.txt](https://github.com/mozilla-iot/zigbee-adapter/files/2368873/ZigbeeCrashLog.txt)

**Comment by dhylands** [comment]
I think that will be fixed by #49 which should be landing tomorrow.

**Comment by AlanDThiessen** [comment]
Thank you.  My Philips Hue bulbs are working as expected.  My Cree bulbs are also working much better with this release too!
